// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcstore

import (
	"database/sql"
)

type User struct {
	ID        int64
	Email     string
	Username  string
	Password  []byte
	UpdatedAt sql.NullTime
	CreatedAt sql.NullTime
}
